# Generated by Django 3.2 on 2021-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='address',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='landmarks',
            name='address',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='address',
            field=models.CharField(default='', max_length=10),
        ),
    ]
