# Generated by Django 3.2 on 2021-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkApp', '0004_auto_20210929_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarks',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='lng',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
