# Generated by Django 3.2 on 2021-09-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkApp', '0005_auto_20210929_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarks',
            name='lat',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='lng',
            field=models.FloatField(max_length=20),
        ),
    ]
