# Generated by Django 3.2 on 2021-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkApp', '0006_auto_20210929_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='lng',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
