# Generated by Django 3.2 on 2021-09-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkApp', '0009_auto_20210929_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmarks',
            old_name='name',
            new_name='building',
        ),
    ]
