# Generated by Django 3.2 on 2021-09-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkApp', '0010_rename_name_landmarks_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmarks',
            old_name='building',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
