# Generated by Django 3.2 on 2021-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkApp', '0012_auto_20210929_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='rank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='represent',
            field=models.CharField(max_length=255),
        ),
    ]
